### ISSUE TITLE
from prefetch_generator import BackgroundGenerator?Can find your implementation?

### ISSUE THREAD

**Issue by TyroneLi** [allenwu97/EDAM#1]

**Comment by allenwu97** [comment]
prefetch_generator is a library, you can install it with following code：
`pip install prefetch_generator`

**Comment by TyroneLi** [comment]
> prefetch_generator is a library, you can install it with following code：
> `pip install prefetch_generator`

Thanks, I fix it now. By the way, could you release code or provide more details for COCO stuff dataset experiments?

**Comment by allenwu97** [comment]
Labels for COCO-Stuff has been uploaded. You should modify https://github.com/allenwu97/EDAM/blob/d0a3482c8f9d88864c51031acc19d1b250b520f1/voc12/data.py#L46 to _cls_labels_coco.npy_
