### ISSUE TITLE
Questions about the  resnet38_EDAM_cls.py

### ISSUE THREAD

**Issue by YeRen123455** [allenwu97/EDAM#10]
Hi @allenwu97 !  Thansk for sharing your nice work! 

I want to reproduce your work but meet the error of "AssertionError" in line 55 of  resnet38_EDAM_cls.py : "assert n == self.mini_batch_size', when I run your code with your default command line:
"python3 train_EDAM_cls.py --lr 0.001 --batch_size 4 --max_epoches 1 --crop_size 368 --network network.resnet38_EDAM_cls --voc12_root [Root of VOC12] --weights [Root of initialization parameters] --wt_dec 5e-4 --session_name resnet38_EDAM_cls
"
Then I try to solve this  problem and remove the above line, but another problem appears:"RuntimeError: The size of tensor a (128) must match the size of tensor b (2) at non-singleton dimension 0" in line 66 of resnet38_EDAM_cls.py.

I notice your dataloader  is different from other WSSS released code. I don't  know how to do with it, can you help me ?  Thanks a lot!

**Comment by allenwu97** [comment]
Your batch_size should be your number of gpus

**Comment by Galaxfyos** [comment]
I have met the same problem,and then change the batch_size to one can solve

**Comment by Galaxfyos** [comment]
your batch_size's default is 8 in code,but the paper said the number of training GPUS is 4

**Comment by YeRen123455** [comment]
@allenwu97 @Galaxfy   Thansk a lot for your kind reply!
