### ISSUE TITLE
Questions about the test result

### ISSUE THREAD

**Issue by squidQAQ** [allenwu97/EDAM#11]
Your EDAM is the experimental result done with the provided weights and the provided train set? (Mean IoU: 68.11) According to your test steps, I only get Mean IoU: 13.29, which part do I Wrong? Hope you can clear my doubts, thanks.

python3 infer_cls.py --infer_list voc12/train.txt --voc12_root ./VOC2012 --network network.resnet38_EDAM_cls --weights ./pretrain_model/download.params  --out_cam_pred cam_pred --out_crf_pred out_crf_pred --theta 0.2  --alpha 0.0025  --beta 0.0095 --sal_path ./saliency_map_train_aug

python3 eval.py --predict_dir out_crf_pred

![2007_002216](https://user-images.githubusercontent.com/96764206/157627926-9f49070b-db5f-4ceb-bd02-807998837b2f.png)

**Comment by allenwu97** [comment]
You should use EDAM_final.pth, download.params is our initial models for training.

**Comment by squidQAQ** [comment]
I think I have something wrong, after using EDAM_final.pth, MIoU becomes 11.59. For the whole project, I only change dataset path and im.convert("P") in colorful.py.

python3 infer_cls.py --infer_list voc12/train.txt --voc12_root ./VOC2012 --network network.resnet38_EDAM_cls --weights ./pretrain_model/EDAM_final.pth --out_cam_pred cam_pred --out_crf_pred out_crf_pred --theta 0.2 --alpha 0.0025 --beta 0.0095 --sal_path ./saliency_map_train_aug

![2007_000768](https://user-images.githubusercontent.com/96764206/157808702-46371a56-21b4-4a81-b8c8-cf685a7d5f00.png)

**Comment by allenwu97** [comment]
Please try --alpha 0.000001  --beta 0.99999

**Comment by squidQAQ** [comment]
I tried --alpha 0.000001 --beta 0.99999, the mIoU becomes 12.137, the problem is still not improved.

python3 infer_cls.py --infer_list voc12/train.txt --voc12_root ./VOC2012 --network network.resnet38_EDAM_cls --weights ./pretrain_model/EDAM_final.pth  --out_cam_pred cam_pred --out_crf_pred out_crf_pred --theta 0.2  --alpha 0.000001  --beta 0.99999 --sal_path ./saliency_map_train_aug/saliency_map_train_aug

![2007_000768](https://user-images.githubusercontent.com/96764206/157816736-fc20797a-1dde-40fe-bf6a-1cb12cbf509c.png)

**Comment by allenwu97** [comment]
Please run 'python3 infer_cls.py --infer_list voc12/train.txt --voc12_root /workdir/VOCdevkit/VOC2012 --network network.resnet38_EDAM_cls --weights [Path of EDAM Parameters]  --out_crf_pred [Output Path]', and eval the results to find out the problem is caused by network or saliency maps.

**Comment by squidQAQ** [comment]
Actually, I have tried without saliency maps,which mIoU is 12.06.

**Comment by allenwu97** [comment]
What is the mIoU of  '--out_cam_pred []  --args.theta 0.5' without saliency maps

**Comment by squidQAQ** [comment]
Use out_cam_pred and theta = 0.5 without saliency maps , which mIoU is 12.304

**Comment by allenwu97** [comment]
Are you sure your network correctly load the pretrained weights? 
What is the output of 'print(model.load_state_dict(torch.load(args.weights)))' (infer_cls.py line 39)

**Comment by squidQAQ** [comment]
I think I know why I can't reproduce your experimental results.
The server I am using has a data connection error. I can reproduce your data after restarting the server.

Thanks for your assistance in my problem.
