### ISSUE TITLE
how can i get the paper?

### ISSUE THREAD

**Issue by lions-heart** [allenwu97/EDAM#2]

**Comment by allenwu97** [comment]
Our paper has been accepted by cvpr2021, we will provide the link when the official release it.

**Comment by allenwu97** [comment]
We now update the links of the paper：https://openaccess.thecvf.com/content/CVPR2021/papers/Wu_Embedded_Discriminative_Attention_Mechanism_for_Weakly_Supervised_Semantic_Segmentation_CVPR_2021_paper.pdf
