### ISSUE TITLE
Questions about DeepLab

### ISSUE THREAD

**Issue by stickyfiner** [allenwu97/EDAM#3]
Hi, thanks for your work. I have some questions about DeepLab. 

1. According to the paper, DeepLab-LargeFOV is used as the segmentation network, however, Deeplab-aspp is used in this project. 
2. Could you please provide more details on training segmentation network.

Thanks.

**Comment by allenwu97** [comment]
Sorry, it is a mistake in our paper. We actually use deeplab-v2 as our segmentation network
For training segmentation network, you just need to replace the gt_labels with pesudo_labels generated by EDAM. We didn't make any changes to the rest of the configuration.
