### ISSUE TITLE
Question about Algorithm 1

### ISSUE THREAD

**Issue by zhaozhengChen** [allenwu97/EDAM#4]
Hi, thanks for your work. I have a question about Algorithm 1.

According to the paper, alpha=0.25, beta=0.95, but in this repo, alpha=0.00001, beta=0.99999

Thanks.

**Comment by allenwu97** [comment]
It depends on whether you use dcrf. If you not use dcrf, the alpha and beta is 0.25 and 0.95. But if dcrf is used, the value of the feature map tends to be binarized, so the values ​​of alpha and beta look _strange_ at this time.

**Comment by zhaozhengChen** [comment]
Thanks
