### ISSUE TITLE
Questions about pretrained models of DeepLab.

### ISSUE THREAD

**Issue by zhaozhengChen** [allenwu97/EDAM#7]
Hi, thanks for your work. 
I wonder which pre-trained models you use for DeepLab.

**Comment by allenwu97** [comment]
We did not change any config which is privided by [Deeplab-v2 Pytorch](https://github.com/kazuto1011/deeplab-pytorch)
So our pre-trained model is trained on MS-COCO

**Comment by zhaozhengChen** [comment]
Thanks for your reply. I get a similar result now.
