### ISSUE TITLE
About weight downloads

### ISSUE THREAD

**Issue by hayaryu** [allenwu97/EDAM#8]
Hi, thanks for your work.
Regarding weights, do you have any plans to share them outside of Baidu?
It is difficult for foreigners to do downloads via Baidu.
(This is the first time I've asked a question in this kind of forum, so I apologize if I'm being rude.)

**Comment by allenwu97** [comment]
Hi, sorry for late reply.
I have uploaded all files to Google Drive, hope this  can help you.

**Comment by hayaryu** [comment]
I was able to download it.
I appreciate very much for your kindness.
